did I madae it right?? ha?? ha ??

diff --git a/.github/workflows/check-linux-musl.yml b/.github/workflows/check-linux-musl.yml
--- a/.github/workflows/check-linux-musl.yml
+++ b/.github/workflows/check-linux-musl.yml
@@ -20,6 +20,12 @@ jobs:
         features: [ "offline", "full", "dev" ]
       fail-fast: false
 
+    env:
+      APP_NAME: "QR2M"
+      APP_PATH: "target/${{ matrix.target }}/release"
+      SIG_FILE: "${{ matrix.features }}.sig"
+      OUTPUT_DIR: "LAB7041/linux-musl"
+
     steps:
       - name: Install system dependencies
         run: |
@@ -58,19 +64,109 @@ jobs:
           echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-musl/pkgconfig:/usr/share/pkgconfig" >> $GITHUB_ENV
           echo "PKG_CONFIG_SYSROOT_DIR=/usr/x86_64-linux-musl" >> $GITHUB_ENV
 
-##Pause
-#      - name: Check code
-#        run: |
-#          cargo fmt --
-#          cargo clippy --no-deps --verbose --locked --features "${{ matrix.features }}" --target ${{ matrix.target }} -- -D warnings
+      - name: Check code
+        run: |
+          cargo fmt --
+          cargo clippy --no-deps --verbose --locked --features "${{ matrix.features }}" --target ${{ matrix.target }} -- -D warnings
 
       - name: Build
         run: cargo build --release --features "${{ matrix.features }}"
 
-##Pause
-#      - name: Run tests
-#        run: cargo test --release --locked --verbose --no-fail-fast --features "${{ matrix.features }}"
+      - name: Run tests
+        run: cargo test --release --locked --verbose --no-fail-fast --features "${{ matrix.features }}"
 
       - name: Verify static linking
         run: |
-          ldd target/x86_64-unknown-linux-musl/release/QR2M || echo "Static binary confirmed"
+          ldd ${{ env.APP_PATH }}/${{ env.APP_NAME }} || echo "Static binary confirmed"
+
+      - name: Versioning
+        run: |
+          VERSION_NUMBER=$(head -n 1 Changelog.md | cut -d ':' -f 2- | tr -d ' #version')
+          if [[ ! "$VERSION_NUMBER" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Error: VERSION_NUMBER is not in valid format: ${VERSION_NUMBER}"
+            exit 1
+          fi
+          echo "VERSION_NUMBER=${VERSION_NUMBER}" | tee -a $GITHUB_ENV
+
+      - name: Import GPG key
+        uses: crazy-max/ghaction-import-gpg@v6
+        with:
+          gpg_private_key: ${{ secrets.ACTIONS_KEY }}
+          passphrase: ${{ secrets.ACTIONS_PASS }}
+          git_user_signingkey: true
+          git_commit_gpgsign: false
+          git_tag_gpgsign: true
+
+      - name: Create tag
+        run: |
+          git config user.name "${{ env.APP_NAME }}"
+          git config user.email "${{ secrets.ACTIONS_EMAIL }}"
+
+          echo "Checking if tag v${{ env.VERSION_NUMBER }} exists..."
+          if ! git rev-parse "v${{ env.VERSION_NUMBER }}" >/dev/null 2>&1; then
+            echo "Tag v${{ env.VERSION_NUMBER }} does not exists."
+            echo "Creating signed tag v${{ env.VERSION_NUMBER }}..."
+            if ! git tag -a "v${{ env.VERSION_NUMBER }}" -s -m "Release v${{ env.VERSION_NUMBER }}"; then
+              echo "GPG signing failed"
+              exit 1
+            fi
+              git push origin "v${{ env.VERSION_NUMBER }}" || {
+                echo "Tag push failed"
+                exit 1
+              }
+              echo "Tag v${{ env.VERSION_NUMBER }} created sucessfully."
+              git ls-remote --tags origin
+            else
+              echo "Tag v${{ env.VERSION_NUMBER }} already exists, skipping"
+          fi
+
+      - name: Signature
+        run: |
+          if [ ! -f "${{ env.APP_PATH }}/${{ env.APP_NAME }}" ]; then
+            echo "Error: Binary not found at ${{ env.APP_PATH }}/${{ env.APP_NAME }}"
+            exit 1
+          fi
+
+          "${{ env.APP_PATH }}/${{ env.APP_NAME }}" & PID=$!
+
+          for i in {1..30}; do
+            [ -f "${{ env.APP_PATH }}/${{ env.APP_NAME }}-${{ env.SIG_FILE }}" ] && { echo "Signature file created: ${{ env.APP_PATH }}/${{ env.APP_NAME }}-${{ env.SIG_FILE }}"; break; }
+            sleep 1
+          done
+
+          if [ ! -f "${{ env.APP_PATH }}/${{ env.APP_NAME }}-${{ env.SIG_FILE }}" ]; then
+            echo "Error: SIG file not found at: ${{ env.APP_PATH }}/${{ env.APP_NAME }}-${{ env.SIG_FILE }}"
+            kill $PID 2>/dev/null || true
+            exit 1
+          fi
+
+      - name: Prepare release files
+        run: |
+          strip target/${{ matrix.target }}/release/${{ env.APP_NAME }}
+          mkdir -p ${{ env.OUTPUT_DIR }}
+
+          cp target/${{ matrix.target }}/release/${{ env.APP_NAME }} \
+            ${{ env.OUTPUT_DIR }}/${{ env.APP_NAME }}-${{ env.VERSION_NUMBER }}-${{ matrix.features }}
+          cp target/${{ matrix.target }}/release/${{ env.APP_NAME }}-${{ matrix.features }}.sig \
+            ${{ env.OUTPUT_DIR }}/${{ env.APP_NAME }}-${{ matrix.features }}.sig
+
+          tar -czf ${{ env.OUTPUT_DIR }}/${{ env.APP_NAME }}-${{ env.VERSION_NUMBER }}-${{ matrix.features }}-${{ matrix.target }}.tar.gz \
+            -C ${{ env.OUTPUT_DIR }} \
+              ${{ env.APP_NAME }}-${{ env.VERSION_NUMBER }}-${{ matrix.features }} \
+              ${{ env.APP_NAME }}-${{ matrix.features }}.sig \
+            -C ../../ \
+              Changelog.md \
+              LICENSE.txt
+
+      - name: Upload to GitHub Releases
+        uses: softprops/action-gh-release@v2
+        with:
+          files: |
+            ${{ env.OUTPUT_DIR }}/${{ env.APP_NAME }}-${{ env.VERSION_NUMBER }}-${{ matrix.features }}-${{ matrix.target }}.tar.gz
+            Changelog.md
+            LICENSE.txt
+          draft: false
+          prerelease: true
+          tag_name: v${{ env.VERSION_NUMBER }}
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
