variables3

diff --git a/.github/workflows/release-linux-gnu.yml b/.github/workflows/release-linux-gnu.yml
--- a/.github/workflows/release-linux-gnu.yml
+++ b/.github/workflows/release-linux-gnu.yml
@@ -23,8 +23,8 @@ jobs:
 
     env:
       APP_NAME: "QR2M"
-      APP_BINARY: "target/${{ matrix.target }}/release/$APP_NAME"
-      SIG_FILE: "APP_BINARY-${{ matrix.features }}.sig"
+      APP_PATH: "target/${{ matrix.target }}/release/"
+      SIG_FILE: "${{ matrix.features }}.sig"
       OUTPUT_DIR: "LAB7041/linux-gnu"
 
     steps:
@@ -46,7 +46,7 @@ jobs:
 
       - name: Check code
         run: |
-          cargo fmt -- --check
+          cargo fmt --
           cargo clippy --no-deps --verbose --locked --features "${{ matrix.features }}" --target ${{ matrix.target }} -- -D warnings
 
       - name: Build
@@ -75,7 +75,6 @@ jobs:
 
       - name: Create tag
         env:
-          VERSION_NUMBER: ${{ env.VERSION_NUMBER }}
           GPG_PRIVATE_KEY: ${{ secrets.ACTIONS_KEY }}
           GPG_KEY_ID: ${{ secrets.ACTIONS_KEY_ID }}
           GPG_PASS: ${{ secrets.ACTIONS_PASS }}
@@ -84,40 +83,40 @@ jobs:
           git config user.name "$APP_NAME"
           git config user.email "$GPG_MAIL"
                    
-          echo "Checking if tag v$VERSION_NUMBER exists..."
-          if ! git rev-parse "v$VERSION_NUMBER" >/dev/null 2>&1; then
-            echo "Tag v$VERSION_NUMBER does not exists."
-            echo "Creating signed tag v$VERSION_NUMBER..."
-            if ! git tag -a "v$VERSION_NUMBER" -s -m "Release v$VERSION_NUMBER"; then
+          echo "Checking if tag v${{ env.VERSION_NUMBER }} exists..."
+          if ! git rev-parse "v${{ env.VERSION_NUMBER }}" >/dev/null 2>&1; then
+            echo "Tag v${{ env.VERSION_NUMBER }} does not exists."
+            echo "Creating signed tag v${{ env.VERSION_NUMBER }}..."
+            if ! git tag -a "v${{ env.VERSION_NUMBER }}" -s -m "Release v${{ env.VERSION_NUMBER }}"; then
               echo "GPG signing failed"
               exit 1
             fi
-              git push origin "v$VERSION_NUMBER" || {
+              git push origin "v${{ env.VERSION_NUMBER }}" || {
                 echo "Tag push failed"
                 exit 1
               }
-              echo "Tag v$VERSION_NUMBER created sucessfully."
+              echo "Tag v${{ env.VERSION_NUMBER }} created sucessfully."
               git ls-remote --tags origin
             else
-              echo "Tag v$VERSION_NUMBER already exists, skipping"
+              echo "Tag v${{ env.VERSION_NUMBER }} already exists, skipping"
           fi
 
       - name: Signature
         run: |
-          if [ ! -f "$APP_PATH" ]; then
-            echo "Error: Binary not found at $APP_PATH"
+          if [ ! -f "$APP_PATH/$APP_NAME" ]; then
+            echo "Error: Binary not found at $APP_PATH/$APP_NAME"
             exit 1
           fi
           
-          "$APP_PATH" & PID=$!
+          "$APP_PATH/$APP_NAME" & PID=$!
           
           for i in {1..30}; do
-            [ -f "$SIG_FILE" ] && { echo "Signature file created: $SIG_FILE"; break; }
+            [ -f "$APP_NAME-$SIG_FILE" ] && { echo "Signature file created: $APP_NAME-$SIG_FILE"; break; }
             sleep 1
           done
 
-          if [ ! -f "$SIG_FILE" ]; then
-            echo "Error: SIG file not found at: $SIG_FILE"
+          if [ ! -f "$APP_NAME-$SIG_FILE" ]; then
+            echo "Error: SIG file not found at: $APP_NAME-$SIG_FILE"
             kill $PID 2>/dev/null || true
             exit 1
           fi
@@ -128,18 +127,18 @@ jobs:
           mkdir -p $OUTPUT_DIR
           cp target/${{ matrix.target }}/release/$APP_NAME $OUTPUT_DIR/$APP_NAME-${{ env.VERSION_NUMBER }}-${{ matrix.features }}
           cp target/${{ matrix.target }}/release/$APP_NAME-${{ matrix.features }}.sig $OUTPUT_DIR/$APP_NAME-${{ matrix.features }}.sig
-          tar -czf $OUTPUT_DIR/$APP_NAME-${{ env.VERSION_NUMBER }}-${{ matrix.features }}-${{ matrix.target }}.tar.gz -C $OUTPUT_DIR \
-            $APP_NAME-${{ env.VERSION_NUMBER }}-${{ matrix.features }} \
-            $APP_NAME-${{ matrix.features }}.sig \
-            Changelog.md \
-            LICENSE.txt
+          tar -czf $OUTPUT_DIR/$APP_NAME-${{ env.VERSION_NUMBER }}-${{ matrix.features }}-${{ matrix.target }}.tar.gz \
+            -C $OUTPUT_DIR \
+              $APP_NAME-${{ env.VERSION_NUMBER }}-${{ matrix.features }} \
+              $APP_NAME-${{ matrix.features }}.sig \
+              Changelog.md \
+              LICENSE.txt
 
       - name: Upload to GitHub Releases
         uses: softprops/action-gh-release@v2
         with:
           files: |
             $OUTPUT_DIR/$APP_NAME-${{ env.VERSION_NUMBER }}-${{ matrix.features }}-${{ matrix.target }}.tar.gz
-            
             Changelog.md
             LICENSE.txt
           draft: false
