refactoring again

diff --git a/.github/workflows/release-macos-aarch64.yml b/.github/workflows/release-macos-aarch64.yml
--- a/.github/workflows/release-macos-aarch64.yml
+++ b/.github/workflows/release-macos-aarch64.yml
@@ -66,6 +66,7 @@ jobs:
 
       - name: Versioning
         run: |
+          set -e
           VERSION_NUMBER=$(head -n 1 Changelog.md | cut -d ':' -f 2- | tr -d ' #version')
           if [[ ! "$VERSION_NUMBER" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
             echo "Error: VERSION_NUMBER is not in valid format: ${VERSION_NUMBER}"
@@ -84,6 +85,7 @@ jobs:
 
       - name: Create tag
         run: |
+          set -e
           git config user.name "${{ env.APP_NAME }}"
           git config user.email "${{ secrets.ACTIONS_EMAIL }}"
 
@@ -107,6 +109,7 @@ jobs:
 
       - name: Signature
         run: |
+          set -e
           if [ ! -f "${{ env.APP_PATH }}/${{ env.APP_NAME }}" ]; then
             echo "Error: Binary not found at ${{ env.APP_PATH }}/${{ env.APP_NAME }}"
             exit 1
@@ -127,6 +130,7 @@ jobs:
 
       - name: Prepare release files
         run: |
+          set -e
           strip target/${{ matrix.target }}/release/${{ env.APP_NAME }}
           mkdir -p ${{ env.OUTPUT_DIR }}
           
@@ -146,35 +150,57 @@ jobs:
       - name: Get existing release assets
         id: existing-assets
         run: |
-          assets=$(gh api /repos/${GITHUB_REPOSITORY}/releases/tags/v${{ env.VERSION_NUMBER }}/assets | jq '.[] | .name')
+          set -e
+          echo "Getting existing release assets..."
+          response=$(gh api /repos/${GITHUB_REPOSITORY}/releases/tags/v${{ env.VERSION_NUMBER }}/assets)
+          echo "Response: $response"
+          if [ $? -ne 0 ]; then
+            echo "Error getting existing release assets: $?"
+            exit 1
+          fi
+          assets=$(echo "$response" | jq '.[] | .name')
+          echo "Assets: $assets"
           echo "assets=$assets" >> $GITHUB_OUTPUT
 
       - name: Check if file already exists
         id: file-exists
         run: |
+          set -e
+          echo "Checking if file already exists..."
           file_name=${{ env.APP_NAME }}-${{ env.VERSION_NUMBER }}-${{ matrix.features }}-${{ matrix.target }}.tar.gz
-          assets=$(jq -r '.assets[] | select(.name == "'"$file_name"'") | .id' <<< ${{ steps.existing-assets.outputs.assets }})
-          if [ -n "$assets" ]; then
+          assets=$(cat $GITHUB_OUTPUT | grep assets | cut -d'=' -f2-)
+          echo "Assets: $assets"
+          if [[ $assets =~ $file_name ]]; then
+            echo "File already exists."
             echo "file_exists=true" >> $GITHUB_OUTPUT
-            echo "asset_id=$assets" >> $GITHUB_OUTPUT
           else
+            echo "File does not exist."
             echo "file_exists=false" >> $GITHUB_OUTPUT
           fi
       
       - name: Calculate hash of new file
         id: new-file-hash
         run: |
+          set -e
+          echo "Calculating hash of new file..."
           file_path=${{ env.OUTPUT_DIR }}/${{ env.APP_NAME }}-${{ env.VERSION_NUMBER }}-${{ matrix.features }}-${{ matrix.target }}.tar.gz
           hash=$(sha256sum "$file_path" | cut -d' ' -f1)
+          echo "New file hash: $hash"
           echo "new_file_hash=$hash" >> $GITHUB_OUTPUT
       
       - name: Get hash of existing file
         id: existing-file-hash
         run: |
+          set -e
+          echo "Getting hash of existing file..."
           if [ "${{ steps.file-exists.outputs.file_exists }}" == "true" ]; then
-            asset_id=${{ steps.file-exists.outputs.asset_id }}
-            hash=$(gh api /repos/${GITHUB_REPOSITORY}/releases/assets/$asset_id | jq -r '.updated_at')
-            echo "existing_file_hash=$hash" >> $GITHUB_OUTPUT
+            file_name=${{ env.APP_NAME }}-${{ env.VERSION_NUMBER }}-${{ matrix.features }}-${{ matrix.target }}.tar.gz
+            response=$(gh api /repos/${GITHUB_REPOSITORY}/releases/tags/v${{ env.VERSION_NUMBER }}/assets | jq '.[] | select(.name == "'"$file_name"'") | .id')
+            asset_id=$(echo "$response" | tr -d '"')
+            echo "Asset ID: $asset_id"
+            existing_hash=$(gh api /repos/${GITHUB_REPOSITORY}/releases/assets/$asset_id)
+            echo "Existing file hash: $existing_hash"
+            echo "existing_file_hash=$existing_hash" >> $GITHUB_OUTPUT
           else
             echo "existing_file_hash=" >> $GITHUB_OUTPUT
           fi
@@ -194,6 +220,7 @@ jobs:
         if: |
           [ "${{ steps.file-exists.outputs.file_exists }}" == "false" ] ||
           [ "${{ steps.new-file-hash.outputs.new_file_hash }}" != "${{ steps.existing-file-hash.outputs.existing_file_hash }}" ]
+
           
       # - name: Upload to GitHub Releases
       #   uses: softprops/action-gh-release@v2
