existing-assets

diff --git a/.github/workflows/release-linux-gnu.yml b/.github/workflows/release-linux-gnu.yml
--- a/.github/workflows/release-linux-gnu.yml
+++ b/.github/workflows/release-linux-gnu.yml
@@ -1,11 +1,15 @@
 name: Release Linux x86_64 GNU
 
 on:
-  workflow_run:
-    workflows: ["Verify GPG Signature"]
-    types:
-      - completed
-    branches: [ "master" ]
+  push:
+    branches:  [ "testing" ]
+  pull_request:
+    branches:  [ "testing" ]
+  # workflow_run:
+  #   workflows: ["Verify GPG Signature"]
+  #   types:
+  #     - completed
+  #   branches: [ "master" ]
 
 permissions:
   contents: write
@@ -75,9 +79,10 @@ jobs:
 
       - name: Create tag
         run: |
+          set -e
           git config user.name "${{ env.APP_NAME }}"
           git config user.email "${{ secrets.ACTIONS_EMAIL }}"
-          
+
           echo "Checking if tag v${{ env.VERSION_NUMBER }} exists..."
           if ! git rev-parse "v${{ env.VERSION_NUMBER }}" >/dev/null 2>&1; then
             echo "Tag v${{ env.VERSION_NUMBER }} does not exists."
@@ -98,6 +103,7 @@ jobs:
 
       - name: Signature
         run: |
+          set -e
           if [ ! -f "${{ env.APP_PATH }}/${{ env.APP_NAME }}" ]; then
             echo "Error: Binary not found at ${{ env.APP_PATH }}/${{ env.APP_NAME }}"
             exit 1
@@ -109,7 +115,7 @@ jobs:
             [ -f "${{ env.APP_PATH }}/${{ env.APP_NAME }}-${{ env.SIG_FILE }}" ] && { echo "Signature file created: ${{ env.APP_PATH }}/${{ env.APP_NAME }}-${{ env.SIG_FILE }}"; break; }
             sleep 1
           done
-
+          
           if [ ! -f "${{ env.APP_PATH }}/${{ env.APP_NAME }}-${{ env.SIG_FILE }}" ]; then
             echo "Error: SIG file not found at: ${{ env.APP_PATH }}/${{ env.APP_NAME }}-${{ env.SIG_FILE }}"
             kill $PID 2>/dev/null || true
@@ -118,9 +124,10 @@ jobs:
 
       - name: Prepare release files
         run: |
+          set -e
           strip target/${{ matrix.target }}/release/${{ env.APP_NAME }}
           mkdir -p ${{ env.OUTPUT_DIR }}
-          
+
           cp target/${{ matrix.target }}/release/${{ env.APP_NAME }} \
             ${{ env.OUTPUT_DIR }}/${{ env.APP_NAME }}-${{ env.VERSION_NUMBER }}-${{ matrix.features }}
           cp target/${{ matrix.target }}/release/${{ env.APP_NAME }}-${{ matrix.features }}.sig \
@@ -134,8 +141,88 @@ jobs:
               Changelog.md \
               LICENSE.txt
 
+      - name: Get existing release assets
+        id: existing-assets
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          set -e
+          echo "Getting existing release..."
+          response=$(gh api /repos/${GITHUB_REPOSITORY}/releases/tags/v${{ env.VERSION_NUMBER }})
+          echo "Response: $response"
+
+          if [ $? -ne 0 ]; then
+            echo "Error getting existing release: $?"
+            exit 1
+          fi
+
+          release_id=$(echo "$response" | jq -r '.id')
+          echo "Release ID: $release_id"
+
+          assets_response=$(gh api /repos/${GITHUB_REPOSITORY}/releases/$release_id/assets)
+          echo "Assets Response: $assets_response"
+
+          if [ $? -ne 0 ]; then
+            echo "Error getting existing assets: $?"
+            exit 1
+          fi
+
+          assets=($(echo "$assets_response" | jq -r '.[] | .name'))
+          echo "Assets: ${assets[@]}"
+          echo "::set-output name=assets;${assets[@]}"
+
+      - name: Check if file already exists
+        id: file-exists
+        run: |
+          set -e
+          echo "Checking if file already exists..."
+          file_name=${{ env.APP_NAME }}-${{ env.VERSION_NUMBER }}-${{ matrix.features }}-${{ matrix.target }}.tar.gz
+
+          if [[ ${{ steps.existing-assets.outputs.assets }} =~ $file_name ]]; then
+            echo "File already exists."
+            echo "file_exists=true" >> $GITHUB_OUTPUT
+          else
+            echo "File does not exist."
+            echo "file_exists=false" >> $GITHUB_OUTPUT
+          fi
+      
+      - name: Calculate hash of new file
+        id: new-file-hash
+        run: |
+          set -e
+          echo "Calculating hash of new file..."
+          file_path=${{ env.OUTPUT_DIR }}/${{ env.APP_NAME }}-${{ env.VERSION_NUMBER }}-${{ matrix.features }}-${{ matrix.target }}.tar.gz
+          hash=$(sha256sum "$file_path" | cut -d' ' -f1)
+
+          echo "New file hash: $hash"
+          echo "new_file_hash=$hash" >> $GITHUB_OUTPUT
+      
+      - name: Get hash of existing file
+        id: existing-file-hash
+        run: |
+          set -e
+          echo "Getting hash of existing file..."
+          if [ "${{ steps.file-exists.outputs.file_exists }}" == "true" ]; then
+            file_name=${{ env.APP_NAME }}-${{ env.VERSION_NUMBER }}-${{ matrix.features }}-${{ matrix.target }}.tar.gz
+            response=$(gh api /repos/${GITHUB_REPOSITORY}/releases/tags/v${{ env.VERSION_NUMBER }}/assets | jq '.[] | select(.name == "'"$file_name"'") | .id')
+            
+            asset_id=$(echo "$response" | tr -d '"')
+            echo "Asset ID: $asset_id"
+            
+            existing_hash=$(gh api /repos/${GITHUB_REPOSITORY}/releases/assets/$asset_id)
+            echo "Existing file hash: $existing_hash"
+            echo "existing_file_hash=$existing_hash" >> $GITHUB_OUTPUT
+          else
+            echo "existing_file_hash=" >> $GITHUB_OUTPUT
+          fi
+
       - name: Upload to GitHub Releases
         uses: softprops/action-gh-release@v2
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        if: |
+          [ "${{ steps.file-exists.outputs.file_exists }}" == "false" ] ||
+          [ "${{ steps.new-file-hash.outputs.new_file_hash }}" != "${{ steps.existing-file-hash.outputs.existing_file_hash }}" ]
         with:
           files: |
             ${{ env.OUTPUT_DIR }}/${{ env.APP_NAME }}-${{ env.VERSION_NUMBER }}-${{ matrix.features }}-${{ matrix.target }}.tar.gz
@@ -144,5 +231,3 @@ jobs:
           draft: false
           prerelease: true
           tag_name: v${{ env.VERSION_NUMBER }}
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
